
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxgrprxyqeuffhczaznl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4Z3Jwcnh5cWV1ZmZoY3phem5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyODk3NDMsImV4cCI6MjA2MDg2NTc0M30.m4p38iF8Wkr_ehuZ4pqWGCcfqKb8cJjrdK-Ni9TO4Cc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
